---
version: 3

env:
    CC: gcc
    CXX: g++

vars:
    BUILD_DIR: ./build
    SOURCE_DIR: .
    BUILD_TYPE: Debug
    TENSE_TEST: "ON"
    TENSE_BENCH: "ON"
    GENERATOR:
        sh: command -v ninja >/dev/null && echo "Ninja" || echo "Unix Makefiles"

tasks:
    clean: rm -fr {{.BUILD_DIR}} CMakeCache.txt

    config:
        deps: [clean]
        cmd: cmake -S{{.SOURCE_DIR}} -B{{.BUILD_DIR}}
            -G"{{.GENERATOR}}"
            -DCMAKE_BUILD_TYPE="{{.BUILD_TYPE}}"
            -DTENSE_TEST="{{.TENSE_TEST}}"
            -DTENSE_BENCH="{{.TENSE_BENCH}}"

    build: cmake --build {{.BUILD_DIR}}

    test:
        deps: [build]
        cmd: "{{.BUILD_DIR}}/test/test"
    bench:
        deps: [build]
        cmd: "{{.BUILD_DIR}}/bench/bench"
